### ISSUE TITLE
Need get API call for Brand, Member 

### ISSUE THREAD

**Issue by Monsoor-Fayas** [Praga-Dev/Paisa-Kanaku#8]
@Praga-Dev Need your input. Please respond

**Comment by Praga-Dev** [comment]
@Monsoor-Fayas 

### Here are the list of calls for the Brand & Member API

![image](https://user-images.githubusercontent.com/86019589/198523333-51207ec2-bb92-4a37-98fd-9961074cda34.png)
![image](https://user-images.githubusercontent.com/86019589/198523529-f6e68f3f-1111-4dc5-a2e3-5bb5461fcafb.png)

**Comment by Monsoor-Fayas** [comment]
Thanks a lot 👍
